/**
 * TypeScript contract for the four publication feeds (spec §Data layer).
 *
 * Generated by hand from the pipeline builders. Two gotchas encoded here:
 *  - `band` is a plain label string (never the full band object).
 *  - `election_cycle_id` differs across feeds (`toronto-2026` vs `toronto_2026`).
 *
 * Fractions are 0..1 (never 0..100) unless a field name says otherwise.
 */

// ── shared enums ────────────────────────────────────────────────────────────

/** `availability` on every forecast quantity card, and in the manifest summary. */
export type Availability =
  | "Forecast Available"
  | "Forecast Unavailable"
  | "Not Applicable";

/** The three quantity kinds. Every `candidate_win` card carries `challenger_win`. */
export type QuantityKind = "challenger_win" | "close_result" | "incumbent_defeat";

// ── 1. mayoral forecast (schema_version 1) ──────────────────────────────────

/** One gated quantity: its tier, availability, published band, and (only when
 *  Available) the point estimate. `band`/`frequency_statement`/`probability` are
 *  null unless `availability === "Forecast Available"`. */
export interface ForecastQuantityCard {
  quantity: QuantityKind;
  candidate_id: string | null;
  tier: string;
  availability: Availability;
  band: string | null;
  frequency_statement: string | null;
  probability: number | null;
  reason: string;
}

export interface MayoralForecastFeed {
  schema_version: 1;
  /** underscore form, e.g. "toronto_2026" */
  election_cycle_id: string;
  evidence_tier: string;
  final_field_samples: string[];
  incumbent_candidate_id: string | null;
  /** keyed by candidate id; includes the incumbent */
  candidate_win: Record<string, ForecastQuantityCard>;
  close_result: ForecastQuantityCard;
  incumbent_defeat: ForecastQuantityCard;
}

// ── 2. mayoral polling (schema_version 1) ───────────────────────────────────

export interface Poll {
  poll_id: string;
  firm: string;
  date_conducted: string;
  date_published: string;
  sample_size: number | null;
  methodology: string;
  field_tested: string[];
  shares: Record<string, number>;
  notes: string;
}

export interface TrendPoint {
  date_conducted: string;
  poll_id: string;
  share: number;
}

export interface MayoralPollingFeed {
  schema_version: 1;
  /** every candidate id appearing in any poll (wider than the current field) */
  candidates: string[];
  /** newest published first */
  polls: Poll[];
  latest: Poll | null;
  /** per-candidate reported share over time, chronological (oldest first) */
  trend: Record<string, TrendPoint[]>;
}

// ── 3. manifest (schema_version 1) ──────────────────────────────────────────

export interface MayoralPublicationSummary {
  evidence_tier: string;
  candidate_win: Record<string, Availability | string>;
  close_result: Availability | string;
  incumbent_defeat: Availability | string;
}

export interface Manifest {
  schema_version: 1;
  generated_at: string;
  election: {
    /** hyphen form, e.g. "toronto-2026" */
    cycle_id: string;
    election_date: string;
    nomination_close_date: string;
    final_ballot_certified: boolean;
  };
  feeds: Record<string, string>;
  feed_versions: Record<string, number>;
  mayoral_publication_summary: MayoralPublicationSummary | null;
}

// ── 4. council race cards (schema_version 2) ────────────────────────────────

export interface Appearance {
  year: number;
  ward: string;
  boundary_era: "44-ward" | "25-ward";
  vote_share: number;
  is_winner: boolean;
}

export interface ExposureTrigger {
  key: string;
  copy: string;
}

export interface Incumbent {
  name: string;
  is_byelection_incumbent: boolean;
  defeatability_score: number | null;
  council_wins: number;
  most_recent_win: Appearance | null;
  exposure_triggers: ExposureTrigger[];
}

export interface FiredHint {
  hint_id: string;
  subject: "own_history" | "opponent_history";
  value: number | null;
  copy: string;
  effect_pp: number;
  ci_low_pp: number;
  ci_high_pp: number;
  effect_unit: string;
  evidence_tier: string;
}

export interface Biography {
  council_wins: number;
  is_former_councillor: boolean;
  most_recent_win: Appearance | null;
  appearances: Appearance[];
}

/** One prior candidacy in a candidate's election history (schema v3, ADR 0050). */
export interface PastElection {
  year: number;
  /** full ISO date; the feed is ordered by this (year is for display) */
  election_date: string;
  office_type: string;
  represented_body: string;
  district_name: string | null;
  party_name: string | null;
  result: "won" | "lost";
  vote_share: number | null;
  rank: number | null;
  field_size: number | null;
}

export interface CouncilCandidate {
  display_name: string;
  status: string;
  candidate_id: string | null;
  is_matched: boolean;
  is_former_councillor: boolean;
  council_wins: number;
  biography: Biography | null;
  historical_hints: FiredHint[];
  /** full prior candidacy history (won and lost), most recent first; empty when
   *  the candidate can't be linked to a person in the canonical dataset */
  past_elections: PastElection[];
}

export interface PriorResult {
  year: number;
  winner_name: string;
  winner_share: number;
  winner_votes: number;
  runner_up_name: string | null;
  runner_up_share: number | null;
  margin_votes: number | null;
  margin_share: number | null;
  field_size: number;
}

export interface Competitiveness {
  field_size: number;
  candidates_who_won_this_ward: number;
  both_won_this_ward: boolean;
  prior_margin_votes: number | null;
  prior_margin_share: number | null;
}

export interface WardPollCandidate {
  candidate_id: string;
  candidate_name: string;
  share: number;
  is_incumbent: boolean;
  is_residual: boolean;
  registration_status: "registered" | "unregistered" | "residual";
}

export interface WardPoll {
  poll_id: string;
  firm: string;
  date_conducted: string;
  date_published: string;
  sample_size: number | null;
  methodology: string;
  denominator: string;
  ballot_status: string;
  undecided_share: number | null;
  candidates: WardPollCandidate[];
}

export interface CouncilRaceCard {
  ward: string;
  ward_name: string | null;
  is_open_seat: boolean;
  incumbent_in_field: boolean;
  incumbency_flag_disagrees: boolean;
  incumbent: Incumbent;
  candidates: CouncilCandidate[];
  prior_result: PriorResult | null;
  competitiveness: Competitiveness;
  ward_polls: WardPoll[];
}

export interface CouncilRaceCardsFeed {
  schema_version: 3;
  base_rate_note: string;
  /** keyed by ward number as a string, "1".."25" */
  wards: Record<string, CouncilRaceCard>;
}
