/**
 * TypeScript contract for the manifest and five publication feeds (spec §Data layer).
 *
 * Generated by hand from the pipeline builders. Two gotchas encoded here:
 *  - `band` is a plain label string (never the full band object).
 *  - `election_cycle_id` differs across feeds (`toronto-2026` vs `toronto_2026`).
 *
 * Fractions are 0..1 (never 0..100) unless a field name says otherwise.
 */

// ── shared enums ────────────────────────────────────────────────────────────

/** `availability` on every forecast quantity card, and in the manifest summary. */
export type Availability =
  | "Forecast Available"
  | "Forecast Unavailable"
  | "Not Applicable";

/** Every `candidate_win` card carries `challenger_win`. */
export type QuantityKind = "challenger_win";

// ── 1. mayoral forecast (schema_version 4, margin-first-joint-draws-v1) ─────

/** One candidate's full-race win probability: the fraction of joint election-day
 *  draws that candidate wins outright. `probability` is null unless
 *  `availability === "Forecast Available"`. No band, no scenarios (ADR 0054). */
export interface ForecastQuantityCard {
  quantity: QuantityKind;
  candidate_id: string;
  tier: string;
  availability: Availability;
  probability: number | null;
  reason: string;
}

export interface ForecastFavouriteCard {
  tier: string;
  availability: "Forecast Available" | "Forecast Unavailable";
  candidate_id: string | null;
  reason: string;
}

/** Election-day full-ballot vote share for one named candidate: the median and
 *  the central `interval_mass` interval of the joint draws, all fractions 0..1. */
export interface ElectionDayCandidate {
  candidate_id: string;
  display_name: string;
  median: number;
  lower: number;
  upper: number;
  win_probability: number;
}

export interface ResidualPoolNamed {
  candidate_id: string;
  display_name: string;
  /** as reported by that poll, a fraction 0..1 */
  latest_polled_share: number;
  poll_id: string;
  date_conducted?: string;
}

/** Every certified candidate outside the modelled named field, as one pool.
 *  It cannot win by construction (`win_probability` is always 0). */
export interface ResidualPool {
  label: string;
  median: number;
  lower: number;
  upper: number;
  win_probability: 0;
  candidate_count: number;
  named_in_polls: ResidualPoolNamed[];
  note: string;
}

/** Probability mass of the signed leader-minus-challenger margin in [left, right)
 *  vote-share points; the last bin's upper edge is closed. */
export interface MarginBin {
  left: number;
  right: number;
  probability: number;
}

/** The published three-way summary of the margin, exact from the draws:
 *  leader ahead by at least the threshold, within the threshold either way,
 *  challenger ahead by at least the threshold. The three sum to one. */
export interface MarginOutcomes {
  close_threshold_points: number;
  leader_ahead: number;
  close: number;
  challenger_ahead: number;
}

export interface PairwiseMargin {
  leader_candidate_id: string;
  challenger_candidate_id: string;
  unit: "vote_share_points";
  median: number;
  lower: number;
  upper: number;
  /** P(challenger's share exceeds the leader's), pairwise — not a win probability */
  probability_challenger_ahead: number;
  outcomes: MarginOutcomes;
  /** audit metadata; the page renders `outcomes`, not the bins */
  bin_width: number;
  range: [number, number];
  bins: MarginBin[];
}

export interface ElectionDay {
  denominator: "full_ballot";
  /** e.g. 0.8 — the central interval carried by every lower/upper pair */
  interval_mass: number;
  statistic: "median";
  /** same order and ids as the `candidate_win` keys */
  candidates: ElectionDayCandidate[];
  residual_pool: ResidualPool;
  pairwise_margin: PairwiseMargin;
}

export type UncertaintySourceKey = "polls_today" | "campaign_movement" | "election_day";

/** leader-minus-challenger gap in full-ballot vote-share points: central interval and who is ahead */
export interface UncertaintyGap {
  median: number;
  lower: number;
  upper: number;
  probability_leader_ahead: number;
  probability_challenger_ahead: number;
}

export interface UncertaintySource extends UncertaintyGap {
  key: UncertaintySourceKey;
  /** this source's variance over the three sources' summed variance; the three add to 1 */
  share_of_uncertainty: number;
}

/**
 * Where the uncertainty comes from (ADR 0056): the leader margin under each source
 * of doubt on its own, applied to today's middle estimate (`centre`), and under all
 * three together (`combined`), which reproduces `pairwise_margin` exactly.
 */
export interface UncertaintyBreakdown {
  leader_candidate_id: string;
  challenger_candidate_id: string;
  unit: "vote_share_points";
  interval_mass: number;
  statistic: "median";
  centre: number;
  /** polls today, campaign movement, election day, each on its own */
  sources: UncertaintySource[];
  combined: UncertaintyGap;
  /** audit: the three sources' summed variance over the combined variance, close to 1 */
  variance_explained: number;
  note: string;
}

export interface ForecastModelRecord {
  name: string;
  version: string;
  specification: Record<string, string>;
  draws: number;
  chains: number;
  seed: number;
  /** true when the fail-closed numerical gate passed; a published feed always carries true */
  qualification_passed: boolean | null;
  [key: string]: unknown;
}

export interface ForecastHistoryPoint {
  /** publication date of the poll(s) that moved the forecast, YYYY-MM-DD */
  date: string;
  poll_sample_ids: string[];
  /** certified-field polls in the model at this point */
  polls: number;
  /** candidate id -> chance of winning (fraction) */
  win_probability: Record<string, number>;
  diagnostics?: Record<string, unknown>;
}

export interface MayoralForecastFeed {
  schema_version: 4;
  publication_policy: "margin-first-joint-draws-v1";
  /** underscore form, e.g. "toronto_2026" */
  election_cycle_id: string;
  /** ISO date of election day */
  election_date: string;
  analysis_cutoff: string;
  evidence_tier: string;
  incumbent_candidate_id: string | null;
  /** the polls the fit used, chronological */
  final_field_samples: string[];
  forecast_favourite: ForecastFavouriteCard;
  /** keyed by candidate id; the modelled named field */
  candidate_win: Record<string, ForecastQuantityCard>;
  /** null only on the development fallback; the validator requires it */
  election_day: ElectionDay | null;
  /** optional and additive (ADR 0056); absent on releases before it was published */
  uncertainty?: UncertaintyBreakdown;
  /** the forecast after each poll release, recomputed with the current model; last point = candidate_win */
  history?: ForecastHistoryPoint[];
  model: ForecastModelRecord;
  /** prespecified alternative refits; audit metadata, never rendered */
  sensitivity: unknown[];
}

// ── 2. Results-owned certified mayoral field (schema_version 5) ─────────────

export type MayoralCareerReviewStatus =
  | "reviewed"
  | "reviewed_with_limitations"
  | "no_verified_prior_candidacy";

export interface MayoralCareerCoverage {
  policy: "full_verified_canadian_electoral_career";
  jurisdiction: "Canada";
  year_cutoff: null;
  cohort_id: string;
  source_release: string;
  review_date: string;
  methodology_note: string;
}

export interface MayoralCandidate {
  candidacy_id: string;
  display_name: string;
  campaign_url: string | null;
  person_id: string | null;
  is_incumbent: boolean;
  review_status: MayoralCareerReviewStatus;
  review_limitations: string | null;
  past_elections: PastElection[];
}

export interface MayoralCandidatesFeed {
  schema_version: 5;
  event_id: string;
  contest_id: string;
  election_date: string;
  ballot_certified: boolean;
  coverage: MayoralCareerCoverage;
  candidates: MayoralCandidate[];
}

// ── Shared presentation-ready race maps ───────────────────────────────────

export type RaceMapSignalKey =
  | "open"
  | "high"
  | "elevated"
  | "quiet"
  | "two_incumbents"
  | "one_incumbent"
  | "acclaimed"
  | "prior_winner_share"
  | "no_comparable_result";

export interface RaceMapLegendEntry {
  key: RaceMapSignalKey;
  label: string;
  description?: string;
}

export interface RaceMapPanel {
  heading: string;
  geography: string;
  status: string;
  candidate_count: number;
  incumbent_summary: string;
  href: string;
}

export interface RaceMapFeature {
  ward_id: string;
  accessible_name: string;
  path: string;
  label: {
    x: number;
    y: number;
    text: string;
    leader_line: null | { x1: number; y1: number; x2: number; y2: number };
  };
  signal_key: RaceMapSignalKey;
  signal_value: number | null;
  panel: RaceMapPanel;
}

export interface RaceMap {
  view_box: "0 0 1000 720";
  aria_label: string;
  palette: "council_attention" | "tdsb_race_structure" | "prior_winner_share";
  legend: RaceMapLegendEntry[];
  features: RaceMapFeature[];
}

// ── Backend-owned trustee race cards (schema_version 3) ───────────────────

export type TrusteeBoardId = "tdsb" | "tcdsb" | "viamonde" | "monavenir";

export interface TrusteeCareerCoverage {
  policy: "verified_toronto_electoral_history_since_2003";
  jurisdiction: "Toronto";
  year_cutoff: 2003;
  cohort_id: string;
  cohort_size: number;
  source_release: string;
  review_date: string;
  methodology_note: string;
}

export interface TrusteeCandidate {
  candidacy_id: string;
  display_name: string;
  campaign_url: string | null;
  person_id: string | null;
  /** True is evidence-backed; null means the feed makes no incumbency claim. */
  is_incumbent: true | null;
  past_elections: PastElection[];
}

export interface TrusteeVoteShareSignal {
  key: "prior_win_under_50";
  subject_person_id: string;
  subject_name: string;
  election_year: number;
  vote_share: number;
}

export type TrusteeRaceContext =
  | {
      method: "tdsb_field_structure";
      category: "open" | "two_incumbents" | "one_incumbent" | "acclaimed";
      sort_priority: 0 | 1 | 2 | 3;
      signal: null;
    }
  | {
      method: "continuous_ward_vote_share";
      category: "open" | "contested_incumbent" | "acclaimed";
      sort_priority: 0 | 2 | 3;
      signal: null;
    }
  | {
      method: "continuous_ward_vote_share";
      category: "won_without_majority";
      sort_priority: 1;
      signal: TrusteeVoteShareSignal;
    };

export interface TrusteeWard {
  contest_id: string;
  ward_id: string;
  district_name: string;
  city_wards: number[];
  result_status: "pending" | "final";
  outcome_method: "pending" | "acclamation";
  acclaimed: boolean;
  comparable_prior_result: PriorResult | null;
  race_context: TrusteeRaceContext;
  candidates: TrusteeCandidate[];
}

export interface TrusteeBoard {
  board_id: TrusteeBoardId;
  represented_body: string;
  display_name: string;
  short_name: string;
  boundary_regime: string;
  candidate_count: number;
  wards: TrusteeWard[];
  map: RaceMap | null;
}

export interface TrusteeRaceCardsFeed {
  schema_version: 3;
  event_id: string;
  election_date: string;
  ballot_certified: boolean;
  coverage: TrusteeCareerCoverage;
  boards: TrusteeBoard[];
}

// ── 3. Polling-owned descriptive feed (schema_version 2) ────────────────────

export interface Poll {
  poll_id: string;
  firm: string;
  date_conducted: string;
  date_published: string;
  sample_size: number | null;
  methodology: string;
  /** public label of the reading's denominator ("Decided and leaning voters", "All respondents"); absent in older releases */
  denominator?: string;
  field_tested: string[];
  shares: Record<string, number>;
  notes: string;
}

export interface TrendPoint {
  date_conducted: string;
  poll_id: string;
  share: number;
}

export interface MayoralPollingFeed {
  schema_version: 2;
  /** every candidate id appearing in any poll (wider than the current field) */
  candidates: string[];
  /** newest published first */
  polls: Poll[];
  latest: Poll | null;
  /** per-candidate reported share over time, chronological (oldest first) */
  trend: Record<string, TrendPoint[]>;
}

// ── 4. deployment source manifest (schema_version 2) ────────────────────────

export interface MayoralPublicationSummary {
  evidence_tier: string;
  publication_policy?: string;
  forecast_favourite?: Availability | string;
  candidate_win: Record<string, Availability | string>;
  pairwise_margin?: { leader_candidate_id: string; challenger_candidate_id: string };
  qualification_passed?: boolean | null;
}

export interface Manifest {
  schema_version: 2;
  /** Time the frontend resolved and verified the immutable release chain. */
  resolved_at: string;
  /** Generation time declared by the selected Backend release. */
  backend_generated_at: string;
  releases: Record<
    "backend" | "results" | "polling",
    {
      repository: string;
      release: string;
      source_commit: string;
      manifest_schema_version: number;
      manifest_sha256: string;
    }
  >;
  feeds: Array<{
    name: string;
    filename: string;
    producer: "backend" | "results" | "polling";
    schema_version: number;
    sha256: string;
  }>;
}

// ── 5. council race cards (schema_version 5) ────────────────────────────────

export interface Appearance {
  year: number;
  ward: string;
  boundary_era: "44-ward" | "25-ward";
  vote_share: number;
  is_winner: boolean;
}

export interface ExposureTrigger {
  key: string;
  copy: string;
}

export interface Incumbent {
  name: string;
  is_byelection_incumbent: boolean;
  defeatability_score: number | null;
  council_wins: number;
  most_recent_win: Appearance | null;
  exposure_triggers: ExposureTrigger[];
  /** CDI components for concrete ward-fact explanations (ticket 05) */
  vote_share: number | null;
  electorate_share: number | null;
  new_voter_margin: number | null;
}

/** Structured provenance behind a fired signal (ADR 0047 amendment / ticket 02). */
export interface SignalSource {
  opponent_name: string | null;
  office_type: string | null;
  year: number | null;
  district_name: string | null;
  result: "won" | "lost" | null;
  rank: number | null;
  field_size: number | null;
  margin: number | null;
  victory_count: number | null;
  qualifying_candidacy_count: number | null;
  /** "resolved" | "measured_zero" */
  coverage: string;
}

export interface FiredHint {
  hint_id: string;
  subject: "own_history" | "opponent_history";
  value: number | null;
  copy: string;
  effect_pp: number;
  ci_low_pp: number;
  ci_high_pp: number;
  effect_unit: string;
  evidence_tier: string;
  /** Binary historical direction; blank for continuous findings without a cutoff. */
  direction: "positive" | "negative" | "";
  source: SignalSource | null;
}

export interface Biography {
  council_wins: number;
  is_former_councillor: boolean;
  most_recent_win: Appearance | null;
  appearances: Appearance[];
}

/** One prior candidacy in a candidate's election history (schema v3, ADR 0050). */
export interface PastElection {
  year: number;
  /** full ISO date; the feed is ordered by this (year is for display) */
  election_date: string;
  office_type: string;
  represented_body: string;
  district_name: string | null;
  /** Results-owned number-plus-geographic label for 2003+ council/trustee races. */
  district_display_name: string | null;
  party_name: string | null;
  result: "won" | "lost";
  vote_share: number | null;
  rank: number | null;
  field_size: number | null;
}

export interface CouncilCandidate {
  candidacy_id: string | null;
  display_name: string;
  status: string;
  candidate_id: string | null;
  campaign_url: string | null;
  is_matched: boolean;
  is_former_councillor: boolean;
  council_wins: number;
  biography: Biography | null;
  historical_hints: FiredHint[];
  /** full prior candidacy history (won and lost), most recent first; empty when
   *  the candidate can't be linked to a person in the canonical dataset */
  past_elections: PastElection[];
}

export interface PriorResult {
  year: number;
  winner_name: string;
  winner_share: number;
  winner_votes: number;
  runner_up_name: string | null;
  runner_up_share: number | null;
  margin_votes: number | null;
  margin_share: number | null;
  field_size: number;
}

export interface Competitiveness {
  field_size: number;
  candidates_who_won_this_ward: number;
  both_won_this_ward: boolean;
  prior_margin_votes: number | null;
  prior_margin_share: number | null;
}

export interface WardPollCandidate {
  candidate_id: string;
  candidate_name: string;
  share: number;
  is_incumbent: boolean;
  is_residual: boolean;
  registration_status: "registered" | "unregistered" | "residual";
}

export interface WardPoll {
  poll_id: string;
  firm: string;
  date_conducted: string;
  date_published: string;
  sample_size: number | null;
  methodology: string;
  denominator: string;
  ballot_status: string;
  undecided_share: number | null;
  candidates: WardPollCandidate[];
}

export interface CouncilRaceCard {
  ward: string;
  ward_name: string | null;
  is_open_seat: boolean;
  incumbent_in_field: boolean;
  incumbency_flag_disagrees: boolean;
  incumbent: Incumbent;
  candidates: CouncilCandidate[];
  prior_result: PriorResult | null;
  competitiveness: Competitiveness;
  ward_polls: WardPoll[];
  attention: {
    level: "high" | "elevated" | "quiet" | "open";
    score: number;
  };
}

export interface CouncilRaceCardsFeed {
  schema_version: 8;
  base_rate_note: string;
  /** keyed by ward number as a string, "1".."25" */
  wards: Record<string, CouncilRaceCard>;
  map: RaceMap | null;
}
