/**
 * TypeScript contract for the manifest and five publication feeds (spec §Data layer).
 *
 * Generated by hand from the pipeline builders. Two gotchas encoded here:
 *  - `band` is a plain label string (never the full band object).
 *  - `election_cycle_id` differs across feeds (`toronto-2026` vs `toronto_2026`).
 *
 * Fractions are 0..1 (never 0..100) unless a field name says otherwise.
 */

// ── shared enums ────────────────────────────────────────────────────────────

/** `availability` on every forecast quantity card, and in the manifest summary. */
export type Availability =
  | "Forecast Available"
  | "Forecast Unavailable"
  | "Not Applicable";

/** The three quantity kinds. Every `candidate_win` card carries `challenger_win`. */
export type QuantityKind = "challenger_win" | "close_result" | "incumbent_defeat";

// ── 1. mayoral forecast (schema_version 2) ──────────────────────────────────

/** One gated quantity: its tier, availability, published band, and (only when
 *  Available) the point estimate. `band`/`frequency_statement`/`probability` are
 *  null unless `availability === "Forecast Available"`. */
export interface ForecastQuantityCard {
  quantity: QuantityKind;
  candidate_id: string | null;
  tier: string;
  availability: Availability;
  band: string | null;
  frequency_statement: string | null;
  probability: number | null;
  reason: string;
}

/** Smoothed density of the winning margin (winner minus runner-up share) across
 *  the Dirichlet draws (schema v2). `x` and `close_threshold` are in share units
 *  (0..1); `density` is the reflected-KDE value at each `x`. Rides on the
 *  close-result gate: the feed sends `null` whenever close_result is withheld. */
export interface MarginDistribution {
  /** "share_gap" — winner minus runner-up, a fraction in [0, 1] */
  unit: string;
  x: number[];
  density: number[];
  /** the "close" cutoff, in the same share units as `x` (e.g. 0.05 = 5 points) */
  close_threshold: number;
  /** Joint winner-and-margin densities on the aggregate grid. Each integrates to
   *  that winner's probability, and all entries sum to the aggregate density. */
  by_winner?: Record<
    string,
    {
      density: number[];
      draw_weight: number;
    }
  >;
}

export interface MayoralForecastFeed {
  schema_version: 2;
  /** underscore form, e.g. "toronto_2026" */
  election_cycle_id: string;
  evidence_tier: string;
  final_field_samples: string[];
  incumbent_candidate_id: string | null;
  /** keyed by candidate id; includes the incumbent */
  candidate_win: Record<string, ForecastQuantityCard>;
  close_result: ForecastQuantityCard;
  incumbent_defeat: ForecastQuantityCard;
  /** null unless close_result publishes (gate-linked; ADR 0006 / 0032) */
  margin_distribution: MarginDistribution | null;
}

// ── 2. Results-owned certified mayoral field (schema_version 3) ─────────────

export type MayoralCareerReviewStatus =
  | "reviewed"
  | "reviewed_with_limitations"
  | "no_verified_prior_candidacy";

export interface MayoralCareerCoverage {
  policy: "full_verified_canadian_electoral_career";
  jurisdiction: "Canada";
  year_cutoff: null;
  cohort_id: string;
  source_release: string;
  review_date: string;
  methodology_note: string;
}

export interface MayoralCandidate {
  candidacy_id: string;
  display_name: string;
  campaign_url: string | null;
  person_id: string | null;
  is_incumbent: boolean;
  review_status: MayoralCareerReviewStatus;
  review_limitations: string | null;
  past_elections: PastElection[];
}

export interface MayoralCandidatesFeed {
  schema_version: 4;
  event_id: string;
  contest_id: string;
  election_date: string;
  ballot_certified: boolean;
  coverage: MayoralCareerCoverage;
  candidates: MayoralCandidate[];
}

// ── Backend-owned trustee race cards (schema_version 1) ───────────────────

export type TrusteeBoardId = "tdsb" | "tcdsb" | "viamonde" | "monavenir";

export interface TrusteeCareerCoverage {
  policy: "verified_toronto_electoral_history_since_2003";
  jurisdiction: "Toronto";
  year_cutoff: 2003;
  cohort_id: string;
  cohort_size: number;
  source_release: string;
  review_date: string;
  methodology_note: string;
}

export interface TrusteeCandidate {
  candidacy_id: string;
  display_name: string;
  campaign_url: string | null;
  person_id: string | null;
  /** True is evidence-backed; null means the feed makes no incumbency claim. */
  is_incumbent: true | null;
  past_elections: PastElection[];
}

export interface TrusteeVoteShareSignal {
  key: "prior_win_under_50";
  subject_person_id: string;
  subject_name: string;
  election_year: number;
  vote_share: number;
}

export type TrusteeRaceContext =
  | {
      method: "tdsb_field_structure";
      category: "open" | "two_incumbents" | "one_incumbent" | "acclaimed";
      sort_priority: 0 | 1 | 2 | 3;
      signal: null;
    }
  | {
      method: "continuous_ward_vote_share";
      category: "open" | "contested_incumbent" | "acclaimed";
      sort_priority: 0 | 2 | 3;
      signal: null;
    }
  | {
      method: "continuous_ward_vote_share";
      category: "won_without_majority";
      sort_priority: 1;
      signal: TrusteeVoteShareSignal;
    };

export interface TrusteeWard {
  contest_id: string;
  ward_id: string;
  district_name: string;
  city_wards: number[];
  result_status: "pending" | "final";
  outcome_method: "pending" | "acclamation";
  acclaimed: boolean;
  comparable_prior_result: PriorResult | null;
  race_context: TrusteeRaceContext;
  candidates: TrusteeCandidate[];
}

export interface TrusteeBoard {
  board_id: TrusteeBoardId;
  represented_body: string;
  display_name: string;
  short_name: string;
  boundary_regime: string;
  candidate_count: number;
  wards: TrusteeWard[];
}

export interface TrusteeRaceCardsFeed {
  schema_version: 1;
  event_id: string;
  election_date: string;
  ballot_certified: boolean;
  coverage: TrusteeCareerCoverage;
  boards: TrusteeBoard[];
}

// ── 3. Polling-owned descriptive feed (schema_version 2) ────────────────────

export interface Poll {
  poll_id: string;
  firm: string;
  date_conducted: string;
  date_published: string;
  sample_size: number | null;
  methodology: string;
  field_tested: string[];
  shares: Record<string, number>;
  notes: string;
}

export interface TrendPoint {
  date_conducted: string;
  poll_id: string;
  share: number;
}

export interface MayoralPollingFeed {
  schema_version: 2;
  /** every candidate id appearing in any poll (wider than the current field) */
  candidates: string[];
  /** newest published first */
  polls: Poll[];
  latest: Poll | null;
  /** per-candidate reported share over time, chronological (oldest first) */
  trend: Record<string, TrendPoint[]>;
}

// ── 4. deployment source manifest (schema_version 1) ────────────────────────

export interface MayoralPublicationSummary {
  evidence_tier: string;
  candidate_win: Record<string, Availability | string>;
  close_result: Availability | string;
  incumbent_defeat: Availability | string;
}

export interface Manifest {
  schema_version: 1;
  generated_at: string;
  releases?: Record<string, { repository: string; release: string; source_commit: string }>;
}

// ── 5. council race cards (schema_version 5) ────────────────────────────────

export interface Appearance {
  year: number;
  ward: string;
  boundary_era: "44-ward" | "25-ward";
  vote_share: number;
  is_winner: boolean;
}

export interface ExposureTrigger {
  key: string;
  copy: string;
}

export interface Incumbent {
  name: string;
  is_byelection_incumbent: boolean;
  defeatability_score: number | null;
  council_wins: number;
  most_recent_win: Appearance | null;
  exposure_triggers: ExposureTrigger[];
  /** CDI components for concrete ward-fact explanations (ticket 05) */
  vote_share: number | null;
  electorate_share: number | null;
  new_voter_margin: number | null;
}

/** Structured provenance behind a fired signal (ADR 0047 amendment / ticket 02). */
export interface SignalSource {
  opponent_name: string | null;
  office_type: string | null;
  year: number | null;
  district_name: string | null;
  result: "won" | "lost" | null;
  rank: number | null;
  field_size: number | null;
  margin: number | null;
  victory_count: number | null;
  qualifying_candidacy_count: number | null;
  /** "resolved" | "measured_zero" */
  coverage: string;
}

export interface FiredHint {
  hint_id: string;
  subject: "own_history" | "opponent_history";
  value: number | null;
  copy: string;
  effect_pp: number;
  ci_low_pp: number;
  ci_high_pp: number;
  effect_unit: string;
  evidence_tier: string;
  /** Binary historical direction; blank for continuous findings without a cutoff. */
  direction: "positive" | "negative" | "";
  source: SignalSource | null;
}

export interface Biography {
  council_wins: number;
  is_former_councillor: boolean;
  most_recent_win: Appearance | null;
  appearances: Appearance[];
}

/** One prior candidacy in a candidate's election history (schema v3, ADR 0050). */
export interface PastElection {
  year: number;
  /** full ISO date; the feed is ordered by this (year is for display) */
  election_date: string;
  office_type: string;
  represented_body: string;
  district_name: string | null;
  party_name: string | null;
  result: "won" | "lost";
  vote_share: number | null;
  rank: number | null;
  field_size: number | null;
}

export interface CouncilCandidate {
  candidacy_id: string | null;
  display_name: string;
  status: string;
  candidate_id: string | null;
  campaign_url: string | null;
  is_matched: boolean;
  is_former_councillor: boolean;
  council_wins: number;
  biography: Biography | null;
  historical_hints: FiredHint[];
  /** full prior candidacy history (won and lost), most recent first; empty when
   *  the candidate can't be linked to a person in the canonical dataset */
  past_elections: PastElection[];
}

export interface PriorResult {
  year: number;
  winner_name: string;
  winner_share: number;
  winner_votes: number;
  runner_up_name: string | null;
  runner_up_share: number | null;
  margin_votes: number | null;
  margin_share: number | null;
  field_size: number;
}

export interface Competitiveness {
  field_size: number;
  candidates_who_won_this_ward: number;
  both_won_this_ward: boolean;
  prior_margin_votes: number | null;
  prior_margin_share: number | null;
}

export interface WardPollCandidate {
  candidate_id: string;
  candidate_name: string;
  share: number;
  is_incumbent: boolean;
  is_residual: boolean;
  registration_status: "registered" | "unregistered" | "residual";
}

export interface WardPoll {
  poll_id: string;
  firm: string;
  date_conducted: string;
  date_published: string;
  sample_size: number | null;
  methodology: string;
  denominator: string;
  ballot_status: string;
  undecided_share: number | null;
  candidates: WardPollCandidate[];
}

export interface CouncilRaceCard {
  ward: string;
  ward_name: string | null;
  is_open_seat: boolean;
  incumbent_in_field: boolean;
  incumbency_flag_disagrees: boolean;
  incumbent: Incumbent;
  candidates: CouncilCandidate[];
  prior_result: PriorResult | null;
  competitiveness: Competitiveness;
  ward_polls: WardPoll[];
}

export interface CouncilRaceCardsFeed {
  schema_version: 6;
  base_rate_note: string;
  /** keyed by ward number as a string, "1".."25" */
  wards: Record<string, CouncilRaceCard>;
}
